version: "3.9"

volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

networks:
  kestra_kestra-net:
    driver: bridge

services:
  postgres_sportif:
    image: postgres:16
    container_name: postgres_sportif
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
      POSTGRES_DB: sportif
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - kestra_kestra-net

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda_sportif
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --overprovisioned
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda_sportif:9092,external://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"
    restart: unless-stopped
    networks:
      - kestra_kestra-net

  postgres:
    image: postgres:18
    container_name: kestra_postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - kestra_kestra-net

  kestra:
    image: kestra/kestra:v1.3.35
    pull_policy: missing
    container_name: kestra
    stop_grace_period: 6m
    user: "root"
    command: server standalone
    env_file:
      - .env
    volumes:
      - ./donnee:/app/data
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd

    environment:
      KESTRA_CONFIGURATION: |
        plugins:
          - io.kestra.plugin.soda
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              username: admin@kestra.io
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/

    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_started

    networks:
      - kestra_kestra-net
